### ISSUE TITLE
Please update for Swift 4

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/Kitura-Session#38]
e.g. update Package.swift

**Comment by gmosx** [comment]
Here is a pull request:
https://github.com/IBM-Swift/Kitura-Session/pull/39

**Comment by tunniclm** [comment]
Hi @gmosx, apologies for the delay in replying here. Swift 4 support had already been added in September under `Package@swift-4.swift` but it wasn't tagged into a release!

On Oct 27 a change was made to make Swift 4 the default, dropping Swift 3 support which was tagged as `2.0.0`.

I'm sorry your issue and PR did not get attention back then :(
Thanks for taking the time to contribute, it is appreciated!
