### ISSUE TITLE
Can't use enum cases in session store

### ISSUE THREAD

**Issue by NocturnalSolutions** [IBM-Swift/Kitura-Session#52]
I think it would be cool if we could do something like…

```swift
public enum UserLevel {
    case admin
    case editor
    case unauthorized
}

// An editor user logs in…

request.session["userLevel"] = UserLevel.editor
```

However, this causes a crash when the session is saved specifically when JSONEncoder tries to encode the store values, since it doesn't like enum values.

For now I'm awkwardly working around this by defining the enum as an Int type (or whatever the proper terminology is) and using rawValue where necessary. But it would be cool if it would "just work." Not sure how it could, though, or else this would be a PR instead of an issue.

**Comment by Andrew-Lees11** [comment]
Hello @NocturnalSolutions, 
For your case can you extend UserLevel to be a string,  (`UserLevel: String`) and the store and retrieve it using the raw value? 
`request.session["userLevel"] = UserLevel.editor.rawValue`

Otherwise you could use typeSafeSession be able to store UserLevel directly if you use Codable routes.

**Comment by NocturnalSolutions** [comment]
Using .rawValue is how I'm working around the issue for now, though I have my enum as an Int rather than a String.

**Comment by Andrew-Lees11** [comment]
I'm not sure how you would be able to store the enum without using raw value. The session is serialized into JSON and an enum isn't valid JSON unless you represent it as an Int or a String. 

 I could look into adding a codable sessions input and output. This would convert from Codable to JSON. For example:
```
request.session.add(UserLevel.editor)
let userLevel = request.session.read(as: UserLevel.self)
```
Without a provided key this needs the codable to a keyed container (E.g. struct/class) .
This would require the following implementation to make your enum Codable:
```
public enum UserLevel: Codable {
    case admin
    case editor
    case unauthorized
    
    enum Key: CodingKey {
        case UserLevel
    }

    enum CodingError: Error {
        case unknownValue
    }
    
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: Key.self)
        let rawValue = try container.decode(Int.self, forKey: .UserLevel)
        switch rawValue {
        case 0:
            self = .admin
        case 1:
            self = .editor
        case 2:
            self = .unauthorized
        default:
            throw CodingError.unknownValue
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: Key.self)
        switch self {
        case .admin:
            try container.encode(0, forKey: .UserLevel)
        case .editor:
            try container.encode(1, forKey: .UserLevel)
        case .unauthorized:
            try container.encode(2, forKey: .UserLevel)
        }
    }
}
```
Alternatively by using a key and raw value you could use the session as:
```
request.session.add(UserLevel.editor.rawValue, forKey: "UserLevel")
let userLevel = request.session.read(as: UserLevel.self, forKey: "UserLevel")
```

For your case I don't think these API would simplify using sessions however they might be useful for storing and retrieving normal structs or classes.

**Comment by Andrew-Lees11** [comment]
I'm going to close this since it is more of an issue with JSONEncoder and JSONDecoder not having the ability to encode or decode fragments. Once either [this](https://bugs.swift.org/browse/SR-6163) is implemented  or we build a dictionary encoder enums can be added. Until then you will have to keep working with coverting to and from raw values of implementing codable yourself as described above.
