### ISSUE TITLE
[Question] does it auto destroy when a session expired?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Kitura-Session#58]
Hi,

i'm not familiar with web session, so I just  try Kitura-Session with Redis.
I have 3 questions.
Q1)I found a lot of expired sessions always keep on Redis server. is it correct?

Q2)the session data(dictionary) does it store in cookie?
      route `post` /user -> request.session?`[user.id] = user`

Q3)How do I know the session data's key(dictionary's key) in browser side?
      route `get` /user -> request.queryParameters["`userid`"]
      the browser never knowns about userid's value 

could give me some advice and thanks

refer to your example
---
```
router.get("/user") { request, response, next in
         guard let userID = request.queryParameters["userid"] else {
            return try response.status(.notFound).end()
         }
         guard let user: User = request.session?[userID] else {
            return try response.status(.internalServerError).end()
         }
         response.status(.OK)
         response.send(user)
         next()
}
```

**Comment by Andrew-Lees11** [comment]
@diuming 
Q1) The Redis server should have a time to live (TTL) parameter that will expire the session after a period of time. I believe redis should clean these up for you.
Q2) The session is persisted using a cookie that is returned to the client. If no cookie name is set it defaults to: "kitura-session-id". When you make future requests with that cookie the corresponding session is attached to the request.
Q3) you are responsible for maintaining the keys used to store objects in a session. In the readme example the user posts a `User` which is stored in the session under for the key `User.id`. The same user is then returned using the query parameter to select the user they want to return. You can save things in the session without user input using fixed keys (E.G. saving an array of books the user has added to their basket in "Books"). The objects stored in the session are then unique to the user.

If you would like to see an example using an in memory store checkout the Kitura sample [Session routes](https://github.com/IBM-Swift/Kitura-Sample/blob/master/Sources/Application/Routes/SessionsRoutes.swift)

**Comment by ianpartridge** [comment]
Question answered - please reopen if you would like to follow up :) Thanks.
