### ISSUE TITLE
Session crashes when receiving invalid data from client

### ISSUE THREAD

**Issue by Kovesar** [IBM-Swift/Kitura-Session#64]
When Session receives tampered data from client side it can crash the whole app if that data is modified in certain ways. Problem is in communication between Kitura-Session and Crypto: Crypto expects that input is valid, and if it is not it just asserts. I guess session should validate data so it conforms to Crypto expectations or Crypto should be modified. 

Repro steps:

1) Run any example that had Session set as middleware. For example this one: [example](https://gist.github.com/Andrew-Lees11/2f1c9bf4f181044298f00ff48545ec03)

2) Use Postman, and modify cookie received from server (see bellow how). Then send another request and the server app will crash.

Cookie can be modified in many ways in order to make app crash. You can modify it in any way that Crypto does not like. Here are two concrete examples:
- Modify one digit in signature part of the session token so that it contains non-hexadecimal digit (e.g. replace hex digit with letter s)
- Replace session token with token "a.b.c"

**Comment by Andrew-Lees11** [comment]
I have raised a [PR](https://github.com/IBM-Swift/BlueCryptor/pull/53) against BlueCryptor to make the byteArray function return an empty array instead of throwing a fatal error. This would fix this issue in a non breaking way since Session would realise this is incorrect and reject the cookie.

**Comment by Andrew-Lees11** [comment]
I closed this issue since the PR against BlueCryptor has been merged and tagged in version 1.0.26. 
Now that it no longer throws a fatal error the Kitura-Session can handle the invalid cookie and your application will no longer crash.
